controller_manager:
  ros__parameters:

    update_rate: 1000

    use_sim_time: true

    joint_controller:
      type: joint_controller/JointController

    joint_forward_trajectory_controller:
      type: joint_forward_trajectory_controller/JointForwardTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    contact_sensors_broadcaster:
      type: contact_sensors_broadcaster/ContactSensorsBroadcaster

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu"


contact_sensors_broadcaster:
  ros__parameters:
    frame_ids:
    - LFF_link
    - RFF_link
    - LRF_link
    - RLF_link
    sensor_names:
    - LFF_contact
    - RFF_contact
    - LRF_contact
    - RRF_contact

joint_forward_trajectory_controller:
  ros__parameters:
    joints:
      - joint_controller/LFT_joint
      - joint_controller/LFH_joint
      - joint_controller/LFK_joint
      - joint_controller/RFT_joint
      - joint_controller/RFH_joint
      - joint_controller/RFK_joint
      - joint_controller/LRT_joint
      - joint_controller/LRH_joint
      - joint_controller/LRK_joint
      - joint_controller/RRT_joint
      - joint_controller/RRH_joint
      - joint_controller/RRK_joint
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

joint_controller:
  ros__parameters:
    joint_names:
      - LFT_joint
      - LFH_joint
      - LFK_joint
      - RFT_joint
      - RFH_joint
      - RFK_joint
      - LRT_joint
      - LRH_joint
      - LRK_joint
      - RRT_joint
      - RRH_joint
      - RRK_joint
    joint_params:
      LFT_joint: 
        position_max: 3.14
        position_min: -3.14
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      LFH_joint: 
        position_max: 10000.0
        position_min: -10000.0
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      LFK_joint: 
        position_max: 2.793
        position_min: -2.793
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      RFT_joint: 
        position_max: 3.14
        position_min: -3.14
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      RFH_joint: 
        position_max: 10000.0
        position_min: -10000.0
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      RFK_joint: 
        position_max: 2.793
        position_min: -2.793
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      LRT_joint: 
        position_max: 3.14
        position_min: -3.14
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      LRH_joint: 
        position_max: 10000.0
        position_min: -10000.0
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      LRK_joint: 
        position_max: 2.793
        position_min: -2.793
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      RRT_joint: 
        position_max: 3.14
        position_min: -3.14
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895
      
      RRH_joint: 
        position_max: 10000.0
        position_min: -10000.0
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      RRK_joint: 
        position_max: 2.793
        position_min: -2.793
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

    frequency: 500.0

    pid_gains:
      LFT_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      LFH_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      LFK_joint:
        p: 120.0
        d: 0.95
        i: 5.0
        ilimit: 0.0
      RFT_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      RFH_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      RFK_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      LRT_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      LRH_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      LRK_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      RRT_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      RRH_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0
      RRK_joint:
        p: 120.0
        d: 0.95
        i: 0.0
        ilimit: 0.0