<?xml version="1.0"?>
<robot name="meldog_core" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="base_properties.urdf.xacro" />
    <xacro:include filename="macros/macros.urdf.xacro" />
    <xacro:include filename="links/trunk.urdf.xacro" />

    <!-- Left front leg links -->

        <!-- Left front hip link -->
        <xacro:include filename="links/hip/LFH_link.urdf.xacro"/>

        <!-- Left front upper limb link -->
        <xacro:include filename="links/upper_limb/LFUL_link.urdf.xacro"/>

        <!-- Left front lower limb link -->
        <xacro:include filename="links/lower_limb/LFLL_link.urdf.xacro"/>

        <!-- Left front foot link -->
        <xacro:include filename="links/foot/LFF_link.urdf.xacro"/>

    <!-- Right front leg links -->

        <!-- Right front hip link -->
        <xacro:include filename="links/hip/RFH_link.urdf.xacro"/>

        <!-- Right front upper limb link -->
        <xacro:include filename="links/upper_limb/RFUL_link.urdf.xacro"/>

        <!-- Right front lower limb link -->
        <xacro:include filename="links/lower_limb/RFLL_link.urdf.xacro"/>

        <!-- Right front foot link -->
        <xacro:include filename="links/foot/RFF_link.urdf.xacro"/>

    <!-- Left rear leg links -->

        <!-- Left rear hip link -->
        <xacro:include filename="links/hip/LRH_link.urdf.xacro"/>

        <!-- Left rear upper limb link -->
        <xacro:include filename="links/upper_limb/LRUL_link.urdf.xacro"/>

        <!-- Left rear lower limb link -->
        <xacro:include filename="links/lower_limb/LRLL_link.urdf.xacro"/>

        <!-- Left rear foot link -->
        <xacro:include filename="links/foot/LRF_link.urdf.xacro"/>


    <!-- Right rear leg links -->

        <!-- Right rear hip link -->
        <xacro:include filename="links/hip/RRH_link.urdf.xacro"/>

        <!-- Right rear upper limb link -->
        <xacro:include filename="links/upper_limb/RRUL_link.urdf.xacro"/>

        <!-- Right rear lower limb link -->
        <xacro:include filename="links/lower_limb/RRLL_link.urdf.xacro"/>

        <!-- Right rear foot link -->
        <xacro:include filename="links/foot/RRF_link.urdf.xacro"/>

    
    <!-- left front leg joints -->
    <joint name="lf_hip_upper_limb_joint" type="revolute">
        <parent link="lf_hip_link" /> 
        <child link="lf_upper_limb_link" />
        <origin xyz="${hip_upper_limb_x}
                     ${hip_upper_limb_y}
                     ${hip_upper_limb_z}" 
                rpy="0 0 0" />
        <limit lower="${hip_upper_limb_lower_limit/180.0*pi}" 
               upper="${hip_upper_limb_upper_limit/180.0*pi}" 
               effort="${hip_upper_limb_effort}" 
               velocity="${hip_upper_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="lf_upper_limb_lower_limb_joint" type="revolute">
        <parent link="lf_upper_limb_link" />
        <child link="lf_lower_limb_link" />
        <origin xyz="0 0 ${-upper_limb_length}" rpy="0 0 0" />
        <limit lower="${upper_limb_lower_limb_lower_limit/180.0*pi}" 
               upper="${upper_limb_lower_limb_upper_limit/180.0*pi}" 
               effort="${upper_limb_lower_limb_effort}" 
               velocity="${upper_limb_lower_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="lf_lower_limb_foot_joint" type="fixed">
        <parent link="lf_lower_limb_link" />
        <child link="lf_foot_link" />
        <origin xyz="0 0 ${-lower_limb_length_to_foot}" rpy="0 0 0" />
    </joint>

    <joint name="lf_trunk_hip_joint" type="revolute">
        <parent link="trunk_link" />
        <child link="lf_hip_link" />
        <origin xyz="${trunk_actuators_length/2.0} ${(trunk_base_width+trunk_actuators_width)/2.0} 0" rpy="0 0 0" />
        <limit lower="${trunk_hip_lower_limit/180.0*pi}" 
               upper="${trunk_hip_upper_limit/180.0*pi}" 
               effort="${trunk_hip_effort}" 
               velocity="${trunk_hip_velocity}" />
        <axis xyz="1 0 0" />
    </joint>


    <!-- Right front leg joints -->
    <joint name="rf_trunk_hip_joint" type="revolute">
        <parent link="trunk_link" />
        <child link="rf_hip_link" />
        <origin xyz="${trunk_actuators_length/2.0} ${-(trunk_base_width+trunk_actuators_width)/2.0} 0" rpy="0 0 0" />
        <limit lower="${trunk_hip_lower_limit/180.0*pi}" 
               upper="${trunk_hip_upper_limit/180.0*pi}" 
               effort="${trunk_hip_effort}" 
               velocity="${trunk_hip_velocity}" />
        <axis xyz="-1 0 0" />
    </joint>

    <joint name="rf_hip_upper_limb_joint" type="revolute">
        <parent link="rf_hip_link" /> 
        <child link="rf_upper_limb_link" />
        <origin xyz="${hip_upper_limb_x}
                     ${-hip_upper_limb_y}
                     ${hip_upper_limb_z}" 
                rpy="0 0 0" />
        <limit lower="${hip_upper_limb_lower_limit/180.0*pi}" 
               upper="${hip_upper_limb_upper_limit/180.0*pi}" 
               effort="${hip_upper_limb_effort}" 
               velocity="${hip_upper_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="rf_upper_limb_lower_limb_joint" type="revolute">
        <parent link="rf_upper_limb_link" />
        <child link="rf_lower_limb_link" />
        <origin xyz="0 0 ${-upper_limb_length}" rpy="0 0 0" />
        <limit lower="${upper_limb_lower_limb_lower_limit/180.0*pi}" 
               upper="${upper_limb_lower_limb_upper_limit/180.0*pi}" 
               effort="${upper_limb_lower_limb_effort}" 
               velocity="${upper_limb_lower_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="rf_lower_limb_foot_joint" type="fixed">
        <parent link="rf_lower_limb_link" />
        <child link="rf_foot_link" />
        <origin xyz="0 0 ${-lower_limb_length_to_foot}" rpy="0 0 0" />
    </joint>


    <!-- Left rear leg joints -->
    <joint name="lr_hip_upper_limb_joint" type="revolute">
        <parent link="lr_hip_link" /> 
        <child link="lr_upper_limb_link" />
        <origin xyz="${-hip_upper_limb_x}
                     ${hip_upper_limb_y}
                     ${hip_upper_limb_z}" 
                rpy="0 0 0" />
        <limit lower="${hip_upper_limb_lower_limit/180.0*pi}" 
               upper="${hip_upper_limb_upper_limit/180.0*pi}" 
               effort="${hip_upper_limb_effort}" 
               velocity="${hip_upper_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="lr_upper_limb_lower_limb_joint" type="revolute">
        <parent link="lr_upper_limb_link" />
        <child link="lr_lower_limb_link" />
        <origin xyz="0 0 ${-upper_limb_length}" rpy="0 0 0" />
        <limit lower="${upper_limb_lower_limb_lower_limit/180.0*pi}" 
               upper="${upper_limb_lower_limb_upper_limit/180.0*pi}" 
               effort="${upper_limb_lower_limb_effort}" 
               velocity="${upper_limb_lower_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="lr_lower_limb_foot_joint" type="fixed">
        <parent link="lr_lower_limb_link" />
        <child link="lr_foot_link" />
        <origin xyz="0 0 ${-lower_limb_length_to_foot}" rpy="0 0 0" />
    </joint>

    <joint name="lr_trunk_hip_joint" type="revolute">
        <parent link="trunk_link" />
        <child link="lr_hip_link" />
        <origin xyz="${-trunk_actuators_length/2.0} ${(trunk_base_width+trunk_actuators_width)/2.0} 0" rpy="0 0 0" />
        <limit lower="${trunk_hip_lower_limit/180.0*pi}" 
               upper="${trunk_hip_upper_limit/180.0*pi}" 
               effort="${trunk_hip_effort}" 
               velocity="${trunk_hip_velocity}" />
        <axis xyz="1 0 0" />
    </joint>

    <!-- Right rear leg joints -->
    <joint name="rr_trunk_hip_joint" type="revolute">
        <parent link="trunk_link" />
        <child link="rr_hip_link" />
        <origin xyz="${-trunk_actuators_length/2.0} ${-(trunk_base_width+trunk_actuators_width)/2.0} 0" rpy="0 0 0" />
        <limit lower="${trunk_hip_lower_limit/180.0*pi}" 
               upper="${trunk_hip_upper_limit/180.0*pi}" 
               effort="${trunk_hip_effort}" 
               velocity="${trunk_hip_velocity}" />
        <axis xyz="-1 0 0" />
    </joint>

    <joint name="rr_hip_upper_limb_joint" type="revolute">
        <parent link="rr_hip_link" /> 
        <child link="rr_upper_limb_link" />
        <origin xyz="${-hip_upper_limb_x}
                     ${-hip_upper_limb_y}
                     ${hip_upper_limb_z}" 
                rpy="0 0 0" />
        <limit lower="${hip_upper_limb_lower_limit/180.0*pi}" 
               upper="${hip_upper_limb_upper_limit/180.0*pi}" 
               effort="${hip_upper_limb_effort}" 
               velocity="${hip_upper_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="rr_upper_limb_lower_limb_joint" type="revolute">
        <parent link="rr_upper_limb_link" />
        <child link="rr_lower_limb_link" />
        <origin xyz="0 0 ${-upper_limb_length}" rpy="0 0 0" />
        <limit lower="${upper_limb_lower_limb_lower_limit/180.0*pi}" 
               upper="${upper_limb_lower_limb_upper_limit/180.0*pi}" 
               effort="${upper_limb_lower_limb_effort}" 
               velocity="${upper_limb_lower_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="rr_lower_limb_foot_joint" type="fixed">
        <parent link="rr_lower_limb_link" />
        <child link="rr_foot_link" />
        <origin xyz="0 0 ${-lower_limb_length_to_foot}" rpy="0 0 0" />
    </joint>

</robot>